name: Build Custom AMI with Packer

on:
  workflow_dispatch:
    inputs:
      ami_version:
        description: "Enter AMI Version (example: v1.0.0)"
        required: true
        default: "v1.0.0"

jobs:
  build-ami:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3

      - name: Verify Packer Version
        run: packer version

      - name: Initialize Packer
        run: packer init packer/

      - name: Validate Packer Template
        run: packer validate -var "ami_version=${{ github.event.inputs.ami_version }}" packer/

      - name: Build Custom AMI
        run: packer build -var "ami_version=${{ github.event.inputs.ami_version }}" packer/
